# Site settings
title: Zxy Blog
SEOTitle: 张晓翼的博客 | Zxy Blog
header-img: img/home-bg.jpg
email: white_joker@hnu.edu.cn
description: "爬虫、反爬、python设计、JAVA设计、C++ | 张晓翼，programmer | 这里是 @张晓翼 的个人博客，此生只做红尘客。"
keyword: "张晓翼, Hnu张晓翼, Hnu, hnupro, @zxypro, 张晓翼的博客, Zxy Blog, 博客, 个人网站, C++, JAVA, Python, 爬虫, 数据结构"
url: "http://www.zxyblog.xyz"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     zxypro
zhihu_username:     zxypro
github_username:    zxypro
twitter_username:   zxypro
#facebook_username:  zxypro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2017, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: zxy

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Read all kinds of documents or codes，<br>One day, watching all the world with the beginning dream!"
sidebar-avatar: /img/avatar-zxy.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub官方网站",
        href: "https://github.com"
    },{
        title: "Jekyll主题",
        href: "http://jekyllthemes.org"
    },{
        title: "Markdown语法手册",
        href: "http://blog.csdn.net/witnessai1/article/details/52551362"
    },{
        title: "C++指针详解",
        href: "http://blog.csdn.net/soonfly/article/details/51131141"
    },{
        title: "最棒的图片素材网站",
        href: "https://www.pexels.com"
    },{
        title: "SQL详解",
        href: "https://www.cnblogs.com/dmh365/archive/2011/08/15/2138967.html"
    },{
        title: "北大oj系统",
        href: "http://poj.org"
    },{
        title: "requests的官方指南文档",
        href: "http://docs.python-requests.org/en/latest/user/quickstart.html"
    }]
